#!/usr/bin/env python3

import os
import sys
from termcolor import cprint

src = sys.argv[1]

def runcmd(cmd):
    code = os.system(cmd)
    if code != 0:
        cprint("FAILED: " + cmd, "red")
        sys.exit(code)

runcmd("mypy " + src)
runcmd("python3 " + " ".join(sys.argv[1:]))
